### ISSUE TITLE
Ability to customize 'amount_of_seconds' in Laravel Blade directive

### ISSUE THREAD

**Issue by robiiinos** [spatie/laravel-honeypot#11]
Hello, I'd like to suggest a new feature; the ability to custom Laravel Blade directive with `amount_of_seconds`.
Let me explain, this would be useful in case where we need to shorten or lengthen the duration required depending on our Form size. For example, a contact form will not require the same time to be filled as a registration form.

This could look like this : 
```php
<!-- Default config; e.g : 5s -->
@honeypot

<!-- Custom config; e.g : 60s -->
@honeypot(60)
```

Thanks for your consideration !

**Comment by freekmurze** [comment]
Send in a fully tested PR for this. If the code is simple enough, I'll consider merging it in 👍
