### ISSUE TITLE
Problem with the middleware

### ISSUE THREAD

**Issue by SaphiLC** [spatie/laravel-honeypot#13]
Whenerever i add the middleware to the kernel.php i get blank pages, even in GET requests, not sure if im doing something wrong or... ill keep it disabled for now but help is appreciated.

**Comment by freekmurze** [comment]
This is indeed a bug, the middleware should only do it's job on post request. Welcoming a PR that takes care of it.

**Comment by SaphiLC** [comment]
#14 hope this fixes the issue, im not very confident with my skills but looks like it works for me
