### ISSUE TITLE
Auth integration

### ISSUE THREAD

**Issue by plindsay** [spatie/laravel-honeypot#28]
Hi, I'm looking to integrate this with Laravel 5.8's built-in auth. I'm not sure how to specify the register method to use the middleware though. Could you clarify how I can do this?

Kind regards.

**Comment by freekmurze** [comment]
I don't know how that integration would look like. This package is primarly designed for forms that can be accessed by guests.

**Comment by noahheck** [comment]
To implement this package with Laravel's `Auth` routes shortcut, I added the middleware to a Route group and it seems to be working successfully:

```php
<?php
// routes/web.php
use \Spatie\Honeypot\ProtectAgainstSpam;

Route::middleware(ProtectAgainstSpam::class)->group(function() {

    Auth::routes();

});
```

The middleware checks for a `POST` request method, so it doesn't interfere with any of the additional Laravel Auth routes, and I added the `@honeypot` directive to each of the auth forms (registration, login, and forgot email).

@freekmurze If you agree that this is good, I'm happy to submit a pull request to add this to usage instructions of the README.

**Comment by freekmurze** [comment]
Yeah sure, send a PR to add this to the docs. 👍
