### ISSUE TITLE
Consider making compatible with laravel-responsecache (or cached pages in general)

### ISSUE THREAD

**Issue by bridgeport** [spatie/laravel-honeypot#32]
Thanks for this package. Have you considered making this compatible with https://github.com/spatie/laravel-responsecache

Like being able to pull the random input names and values in via AJAX and setting the input field names and values with client-side JavaScript?

For instance, CSRF tokens can't be embedded with cached pages, so a workaround is to pull the CSRF token with an ajax request onsubmit, such as:

```php
Route::get('/get-csrf-token', function () {
    return csrf_token();
});
```

Perhaps something like this could be done with honeypot? Where a call to a URL could provide an array of the necessary names and values?

Thanks.

**Comment by freekmurze** [comment]
Yes, we considered making some adjustments in responsecache so it plays nice with honeypot and our csp packages. Unfortunately we don't have the time to look into this now. 

I'd welcome a PR on responsecache that makes it compatible with both honeypost and csp packages.
