### ISSUE TITLE
Handling ajax-requests with serialized form params

### ISSUE THREAD

**Issue by romansidorov** [spatie/laravel-honeypot#33]
Hello! I have a form that is handled with ajax:

```
$.ajax({
        url: $form.attr('action'),
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        },
        type: 'post',
        dataType: 'json',
        data: {
            fields: $form.serialize()
        },
        success: function(response){
            //
        }
    });
```

Inside the form I use honeypot-fields with names randomizing.

Can I use this package in my case? It seems that the middleware expects to recieve honeypot-fields in request(), but since I serialize the form, the middleware can not find these fields. How should I act with it?

Thank you!

**Comment by amberlampsio** [comment]
make sure you use the latest version of honey pot, previously it was using a "dash" (-) as a dilimiter, which is not supported as a json key... 

https://github.com/spatie/laravel-honeypot/commit/bc900b835ea49d5acf6ac692220746c137822359
