### ISSUE TITLE
Global middleware and form without honeypot 

### ISSUE THREAD

**Issue by apair** [spatie/laravel-honeypot#34]
Hey,
If 
-  `ProtectAgainstSpam::class` as a global http middleware on Kernel.php was set
-  You have a form that has no `@honeypot` 
- `honeypot.randomize_name_field_name` config was set to true

then when form submit , the middleware detects it as spam.
It because of empty result of $this->getRandomizedNameFieldName on ProtectAgainstSpam middleware.

**Comment by freekmurze** [comment]
Don't have time to look into this name, but feel free to submit a PR with tests that fixes this.

**Comment by apair** [comment]
I just look at `ProtectAgainstSpamTest` files and see in `requests_that_not_use_the_honeypot_fields_succeed()` test.
In the first line, 'honeypot.randomize_name_field_name' config was set to false and that is why this bug passed the test.
I wonder why this config should set to false when a form does not use `@honeypot`?

**Comment by atymic** [comment]
I'll look into fixing this :)

**Comment by freekmurze** [comment]
We'll continue this conversation in #36
