### ISSUE TITLE
Registering the middle with Laravel's own auth 

### ISSUE THREAD

**Issue by blorange2** [spatie/laravel-honeypot#35]
Hi,

In the documentation it says this middleware can be registered with the path `\Spatie\Honeypot\ProtectAgainstSpam::class`

So I registered it in `protected $routeMiddleware` like so:

    protected $routeMiddleware = [
        ...
        'honey_pot' => \Spatie\Honeypot\ProtectAgainstSpam::class,
    ];

In my `RegisterController` I attached this to the `create` method like so:

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('honey_pot')->only('create');
    }

However, the middleware does not run when registering.

**Comment by atymic** [comment]
The `create` method on the controller is not correct. This is the private function called to create the user
```php
protected function create(array $data)
```

You need to add the middleware to the `register` method:

```php
/**
* Handle a registration request for the application.
*
* @param  \Illuminate\Http\Request  $request
* @return \Illuminate\Http\Response
*/
public function register(Request $request)
```
