### ISSUE TITLE
Consider requiring php 7.1 instead of 7.2

### ISSUE THREAD

**Issue by samtny** [spatie/laravel-honeypot#37]
Php 7.2 makes Laravel development on a Mac a little more difficult, as MacOS Sierra has PHP 7.1 pre-installed.

**Comment by freekmurze** [comment]
Please upgrade your PHP version.

**Comment by samtny** [comment]
I may do that, but do note that Laravel itself requires only PHP 7.1.3.

**Comment by jamiehd** [comment]
@freekmurze what is the reason for the minimum version requirements? Are you using particular features from 7.3?
