### ISSUE TITLE
L5.8 @honeypot not working

### ISSUE THREAD

**Issue by RosiersRobin** [spatie/laravel-honeypot#38]
Hi,

I tried to install the package on Laravel 5.8, but when I add `@honeypot`, it never gets parsed, it just displays plain `@honeypot` in the view....

Any ideas on how to solve this?

**Comment by vdbelt** [comment]
I just tried installing this package on a fresh install of L5.8, and couldn't replicate your issue. 

Have you made sure the package was installed correctly, and made sure it isn't disabled?

**Comment by RosiersRobin** [comment]
I have, I tried reïnstalling it, still the same issue, can it conflict with other packages in this list?

```json
"benjamincrozat/laravel-dropbox-driver": "^2.0",
        "beyondcode/laravel-mailbox": "^1.2",
        "cviebrock/eloquent-sluggable": "4.8",
        "fideloper/proxy": "^4.0",
        "ijin82/flysystem-webdav": "^1.0",
        "it-brains/queue-job-logger": "^0.1.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "lorisleiva/laravel-deployer": "^0.2.11",
        "predis/predis": "^1.1",
        "spatie/laravel-analytics": "^3.6",
        "spatie/laravel-backup": "^6.0",
        "spatie/laravel-cookie-consent": "^2.6",
        "spatie/laravel-permission": "^2.28",
        "spatie/laravel-responsecache": "^4.4",
        "spatie/laravel-server-monitor": "^1.6",
        "spatie/laravel-sitemap": "^5.2",
        "squizlabs/php_codesniffer": "*",
        "yoeunes/toastr": "^1.1"
```

**Comment by RosiersRobin** [comment]
As a follow-up, the package is enabled, but the `@honeypot` isn't parsed.

**Comment by jasonhld** [comment]
> As a follow-up, the package is enabled, but the `@honeypot` isn't parsed.

I ran this as` @honeypot()` instead of just `@honeypot` and then ran `php artisan view:clear`. Not sure which fixed it, but it did.

**Comment by RosiersRobin** [comment]
> > As a follow-up, the package is enabled, but the `@honeypot` isn't parsed.
> 
> I ran this as` @honeypot()` instead of just `@honeypot` and then ran `php artisan view:clear`. Not sure which fixed it, but it did.

Tried both ` @honeypot()` and `@honeypot` followed by the `php artisan view:clear` command. Still nothing works.

My form is like:

```
 <form action="{{ url('contact') }}" method="post">
    @csrf
    @honeypot
    <input>
 </form>
```

**Comment by rcubitto** [comment]
I assume the service provider is being auto-detected. I'd try to `dd()` right before the directive is defined to assert it is being called.

https://github.com/spatie/laravel-honeypot/blob/master/src/HoneypotServiceProvider.php#L28

**Comment by aedsas** [comment]
I had the same problem, turns out there was some kind of conflict with another package ('htmlmin/htmlmin').

I disabled htmlmin/htmlmin, cleared caches/etc. then enabled everything again and now everything works correctly!

**Comment by RosiersRobin** [comment]
So it was a strange cache issue.... I had to remove all te cached files manually and then it worked...
