### ISSUE TITLE
@honeypot blade directive not working in laravel 6.0

### ISSUE THREAD

**Issue by Marbo1756** [spatie/laravel-honeypot#41]
The `@honeypot` blade directive just displays "`@honeypot`" in the form without adding the expected input fields.

**Comment by rcubitto** [comment]
The directive is `@honeypot` without spaces between the `@` and `honeypot`.

**Comment by Marbo1756** [comment]
> The directive is `@honeypot` without spaces between the `@` and `honeypot`.

I know I just didn't want to tag the guy named honeypot and forgot that I can just label `@honeypot` as code. The issue still persists.

**Comment by freekmurze** [comment]
The tests indicate that the directive is working as intended. Could you try installing the package in a new Laravel project?

**Comment by Marbo1756** [comment]
It works now despite me changing anything. Weird. But thanks for the help anyway.

**Comment by nickdekruijk** [comment]
I just had the same issue, had to do `php artisan view:clear` to fix it.
