### ISSUE TITLE
How do I use this???

### ISSUE THREAD

**Issue by novafragger** [spatie/laravel-honeypot#44]
You know I am all for the making of good packages however I have tried everything and keep coming up short with making this work on Laravel 6.3...

Blade does not recognize @honeypot as anything, when I view the page source there is nothing but the @csrf directive.

I tried linking the standard laravel auth routs as specified however the below is the outcome...
Illuminate\Contracts\Container\BindingResolutionException
Target [Spatie\Honeypot\SpamResponder\SpamResponder] is not instantiable while building [Spatie\Honeypot\ProtectAgainstSpam].

There is no support on this

HOW DO I USE THIS, THIS IS SO FRUSTRATING

**Comment by novafragger** [comment]
This is because of conflicting issues ... the hell man, can someone post a list of conflicting packages?

**Comment by smeranda** [comment]
What were your conflicts? I'm having a similar issues.

**Comment by novafragger** [comment]
Hi seth, the screw up is that honeypot needs to be the first package you
install, and then all your other packages, I had to redo 10 months of work
because of this
