### ISSUE TITLE
Dead tutorial link

### ISSUE THREAD

**Issue by JonasPardon** [spatie/laravel-honeypot#48]
Hi guys,

In the README, there's a link to a video tutorial (https://vimeo.com/381197983) on how to use this package. I'm assuming since it's now included in the mailcoach premium video course package, it has been moved?

Either way, the link is dead, and I'm not sure that's what you guys intended.

**Comment by freekmurze** [comment]
I've made the video public again.

**Comment by JonasPardon** [comment]
Works again! Thanks!
