### ISSUE TITLE
Checking if honeypot field exists in request

### ISSUE THREAD

**Issue by mrk-j** [spatie/laravel-honeypot#51]
Hi,

Last week we started testing this package. We noticed some spam still coming through, when investigating and reading through the middleware I saw there isn't a check to check if the honeypot field is present in the request. 

Is this a choice you made on purpose or is this something that can be improved? If you think this is an improvement I can send in a PR.

Thank you!

**Comment by freekmurze** [comment]
Feel free to PR improvements, make sure to include tests as well! 👍

**Comment by den1n** [comment]
Why this PR is accepted? It turn Honeypot logic upside down.

README says: "you must add the @honeypot blade directive to any form you wish to protect". "This middleware will intercept any request that submits a non empty value for the key named my_name".

Previously logic was: if blade directive @honeypot is exists then Honeypot protects form from spam.
Now Honeypot tries to protect all the forms even without @honeypot directive in it.

With this PR megred, theres no way of enabling Honeypot in app and have forms without Honeypot fields.

For example, now with fresh Laravel installation and Honeypot enabled in App\Http\Kernel or through wrapping Auth::routes() in middleware the default Laravel auth controller does not work propertly. All POST forms (login, register, etc) are broken now and leads to blank page.

This PR completely broke the previous logic of the package.
