### ISSUE TITLE
Confusion on Laravel 6 support with laravel-honeypot 2.1.0

### ISSUE THREAD

**Issue by vendion** [spatie/laravel-honeypot#53]
In the release notes for laravel-honeypot 2.1.0 it mentions the following

> drop support for anything below Laravel 6

My read on that is that Laravel 6.x, which is an LTS release, should still be supported but in the package's _composer.json_ file you have the following:

```
"laravel/framework": "^7.0",
```

Meaning that support for anything below Laravel 7 is dropped.

**Comment by freekmurze** [comment]
We are not required to follow the LTS policy.

Feel free to fork our package, and invest some time if you need Laravel 6 compatibility.

**Comment by vendion** [comment]
I was more curious if the release notes for 2.1.0 where incorrect, due to the verbage hinting at Laravel 6.x was still support.

Maybe your release notes should be worded as "Dropped support for Laravel 6 and older" or "Dropped support for anything below Laravel 7". While I understand that you do not have to support Laravel's LTS release cycles I proper change log for your releases would be nice.

**Comment by freekmurze** [comment]
Fixed! If you spot other things that can be improved or corrected, feel free to send a PR! 👍
