### ISSUE TITLE
Can't install package.

### ISSUE THREAD

**Issue by gdemos01** [spatie/laravel-honeypot#55]
When I run composer require spatie/laravel-honeypot I get the following error:
 (Works on Windows, doesn't work on Ubuntu)

> Problem 1
>     - Can only install one of: laravel/framework[v5.8.37, 7.x-dev].
>     - Can only install one of: laravel/framework[7.x-dev, v5.8.37].
>     - Can only install one of: laravel/framework[7.x-dev, v5.8.37].
>     - spatie/laravel-honeypot 2.1.0 requires laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev].
>     - Installation request for spatie/laravel-honeypot ^2.1 -> satisfiable by spatie/laravel-honeypot[2.1.0].
>     - Installation request for laravel/framework (locked at v5.8.37, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.37].

**I do have a Laravel framework > 5.8. 
Of course when I added manually: "spatie/laravel-honeypot": "^1.3", in controller it works.**

**Comment by gdemos01** [comment]
Composer file

>   "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "aws/aws-sdk-php": "^3.112",
        "aws/aws-sdk-php-laravel": "~3.0",
        "core/administrative": "dev-master",
        "core/creatorstudio": "dev-master",
        "core/searchengine": "dev-master",
        "core/socialnetwork": "dev-master",
        "core/subscriptionsystem": "dev-master",
        "enyo/dropzone": "^5.5",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "league/flysystem-aws-s3-v3": "~1.0",
        "spatie/laravel-permission": "^2.38",
        "yajra/laravel-datatables-oracle": "~9.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    

    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by michellaurent** [comment]
@gdemos01 You have to specify the right version. Version 2.1.0 requires Laravel 7.

composer require spatie/laravel-honeypot:1.3.0
