### ISSUE TITLE
PR #52 turn Honeypot logic upside down

### ISSUE THREAD

**Issue by den1n** [spatie/laravel-honeypot#57]
Why PR #52 is accepted?

Your README says: "you must add the @ honeypot blade directive to any form you wish to protect". "This middleware will intercept any request that submits a non empty value for the key named my_name".

Previously logic was: if blade directive @ honeypot is exists then Honeypot protects the form.
Now Honeypot tries to protect all the forms even without @ honeypot directive in it.

With this PR megred theres no way of enabling Honeypot in app and have forms without Honeypot fields.

For example, now with fresh Laravel installation and Honeypot enabled in App\Http\Kernel or through wrapping Auth::routes() in middleware the default Laravel auth controller does not work propertly. All POST forms (login, register, etc) are broken now and leads to blank page.

PR #52 completely broke previous logic of the package.

**Comment by freekmurze** [comment]
My reasoning for accepting the PR was: "oh yeah, bots could just filter out the honeypot fields and that way make submissions, let's fix that".

But you're right that this is a breaking change that should be addressed. I'd accept a PR that reverses #52. If such a PR doesn't come in, I'll try to take care of it next week.

I'll also release a new major version that has the current logic, but also adds a config option to have the behaviour before #52 was merged.

**Comment by den1n** [comment]
Thanks for the explanation.
Guess i'll wait then for new release.

**Comment by rubenvanassche** [comment]
Hi guys, we fixed this with release 2.2.0! Will close this issue for now
