### ISSUE TITLE
Honeypot prevents laravel native auth redirects

### ISSUE THREAD

**Issue by megavolkan** [spatie/laravel-honeypot#61]
I installed honeypot 2.0.0 on Laravel 5.8 project. I also use laravel's native auth for my admin panel, and my logins work normally. As soon as i include ` \Spatie\Honeypot\ProtectAgainstSpam::class,` in Kernel.php $middleware the auth redirects stop working. When username and password inputs filled and submitted it displays a blank screen with URI stuck at /login, not redirected to /admin (after login page) as expected. When removed  `\Spatie\Honeypot\ProtectAgainstSpam::class` from middlewares everything turns to normal. 
I followed all the instructions. I only use honeypot on my frontend contact forms, not using on any of admin pages. Although i tried wrapping `Auth::routes();` in `Route::middleware(ProtectAgainstSpam::`.... it didn't work either. 
Even though the auth functions stopped working, @honeypot directives on my frontend pages work perfectly on my tests.

**Comment by marsvin** [comment]
Could it be a 502 error you get after submit? It might be that the response headers are too big so nginx runs out of memory when receiving from PHP-FPM.

I had this issue on a route using honeypot (the only route using it and the only route not working as it generated a 502 error).

The honepot protected route worked fine when testing on the Homestead server, but on the live server it did not work.

I had to change my nginx.conf by adding the following lines:

```
fastcgi_buffers 8 8k;
fastcgi_buffer_size 8k; 
```
See this [SO answer for more](stackoverflow.com/questions/23844761/upstream-sent-too-big-header-while-reading-response-header-from-upstream)

Be aware that you should not increase the memory usage more than needed. The example on stackoverflow might be overkill. In the comment there is a link to more on selecting the ideal values.

**Comment by megavolkan** [comment]
Well, i’m on apache not nginx if that makes a difference. And do not suppose it is related to a 502 error because the response is immediate. In case of a memory related 502 error there should be at least a slight (but viewable) delay before response. I wonder if tehere is there some kind of error reporting/logging for honeypot?

**Comment by freekmurze** [comment]
Closing this as we don't support Laravel 5.8 anymore
