### ISSUE TITLE
How to generate `@honeypot` in controller?

### ISSUE THREAD

**Issue by lovecoding-git** [spatie/laravel-honeypot#62]
First of all, thanks for such great package.
I am using this  honeypot in my laravel project and now I have one question.
How can I generate @honeypot in my controller?
Is there any alternative way for it?

Now in my controller, I am passing full form elements to view and just wondered how to pass @honeypot field.

Thank you.

**Comment by freekmurze** [comment]
You can use `view('honeypot::honeypotFormFields')->render()`

**Comment by lovecoding-git** [comment]
Thanks! It worked!!!
