### ISSUE TITLE
fresh composer install of spatie/laravel-honeypot has mismatched + missing files

### ISSUE THREAD

**Issue by feraar** [spatie/laravel-honeypot#69]
Fresh install of laravel v8 
Composer require spatie/laravel-honeypot

composer.json shows version as;
```json
...
"spatie/laravel-honeypot": "^2.3"
...
```

vendor folder content does not match the github repo files
cleared vendor files few times and did composer update - same outcome

Seems like I ending up with an earlier version.
My src folder has only 1 sub folder SpamResponder
The src folder also includes HoneypotViewComposer.php file.

**Comment by freekmurze** [comment]
I cannot reproduce this. It seems to just work here.

**Comment by freekmurze** [comment]
Seems like v3 was not tagged correctly. If you try again, it should work.

**Comment by feraar** [comment]
Working fine now. Thanks
