### ISSUE TITLE
Jetstream/ Inertia ProtectAgainstSpam::handle() Symfony Response expected, LoginResponse returned

### ISSUE THREAD

**Issue by P-James** [spatie/laravel-honeypot#75]
When using the ProtectAgainstSpam middleware in a Jetstream/ Fortify/ Inertia set up, the following error occurs:  

`Spatie\Honeypot\ProtectAgainstSpam::handle(): Return value must be of type Symfony\Component\HttpFoundation\Response, App\Http\Responses\LoginResponse returned`  

I solved it by removing the return type on the handle method but would be interested to know a more robust way of solving this. I'd happily PR it, just may need a some guidance as it's a bit deeper than I've gone before. I'm guessing we could return a common interface instead of a concrete Response class?

**Comment by freekmurze** [comment]
Strange, doesn't `App\Http\Responses\LoginResponse` extend `Symfony\Component\HttpFoundation\Response`

Because the package is PHP 8 only, we could use union types. We could just add `LoginResponse` to the list of return values.

**Comment by P-James** [comment]
`App\Http\Responses\LoginResponse` implements `Illuminate\Contracts\Support\Responsable` which returns a (non-typed) `\Symfony\Component\HttpFoundation\Response`

I made a [PR adding Fortify dep and union type](https://github.com/spatie/laravel-honeypot/pull/76)

**Comment by freekmurze** [comment]
Fixed in v4, thanks for the help @P-James
