### ISSUE TITLE
Installation instructions out of date

### ISSUE THREAD

**Issue by dwightwatson** [spatie/laravel-honeypot#88]
The installation instructions show how to publish the configuration file:

```
php artisan vendor:publish --provider="Spatie\Honeypot\HoneypotServiceProvider" --tag=config
```

However this doesn't work as there aren't any resources for the `config` tag:

```
No publishable resources for tag [config].
Publishing complete.
```

I suspect this is is because of `LaravelPackageTools` - there's a call to [`hasConfigFile` here](https://github.com/spatie/laravel-honeypot/blob/master/src/HoneypotServiceProvider.php#L15-L21) but I guess it doesn't apply the tag name as well.

Not sure if there's a way to set the tag through the package tools, or if the documentation should just be updated to remove the `--tag=config` component.

**Comment by freekmurze** [comment]
Does the tag `honeypot-config` work for you?

**Comment by dwightwatson** [comment]
Yeah, that does the trick.

```
php artisan vendor:publish --provider="Spatie\Honeypot\HoneypotServiceProvider" --tag=honeypot-config

Copied File [/vendor/spatie/laravel-honeypot/config/honeypot.php] To [/config/honeypot.php]
Publishing complete.
```

Want me to PR a change the docs?

**Comment by freekmurze** [comment]
You, PR it! 👍
