### ISSUE TITLE
Documented command to publish config does not work

### ISSUE THREAD

**Issue by duncanmcclean** [spatie/laravel-honeypot#90]
In the `README.md` documentation for this package, it mentions that you can publish the package's config using the following command:

```
php artisan vendor:publish --provider="Spatie\Honeypot\HoneypotServiceProvider" --tag=honeypot-config
```

However, when you try that, you get this:

```
No publishable resources for tag [honeypot-config].
Publishing complete.
```

If I run `php artisan vendor:publish` to see the full list of available publishable things, `honeypot-config` is not mentioned. To publish the config file in the end, I had to publish from the service provider.

**Comment by freekmurze** [comment]
Have you made sure you are running the latest version?

**Comment by duncanmcclean** [comment]
Yes, I had only just installed the package for the first time.

**Comment by duncanmcclean** [comment]
Strange, for whatever reason, it seemed to install 3.0.1 instead of 4.0.0 which is the latest 🤔

**Comment by duncanmcclean** [comment]
Oh probably because 4.0.0 requires PHP 8 and I'm using PHP 7.4 🤦
