### ISSUE TITLE
Honeypot spam trap conflicts with chrome auto-fill

### ISSUE THREAD

**Issue by OmarBouziane** [spatie/laravel-honeypot#96]
Hey,

When I use honeypot I can't submit the form in google chrome, when the trap input is being auto-filled. 
Unfortunately, google chrome doesn't support autocomplete="off", or "false".

Thank you.

**Comment by freekmurze** [comment]
We haven't notices this issue ourselves yet, feel free to submit a PR that would solve the problem for you.

**Comment by OmarBouziane** [comment]
Now, with google chrome, when I submit the form, the random string added to the name_field_name within the props and the form doesn't change, same string for both. But when I use firefox, it changes, I mean the string added to the name_field_name in props isn't the same in the form.
I am using the last version of Inertia.

**Comment by StApostol** [comment]
@freekmurze When I used HONEYPOT_NAME=user_data, chrome insert data in this field (maybe used username/login data from saved information for this field)
Solved changed HONEYPOT_NAME to another value
